### ISSUE TITLE
Error launching details: Host does not support domain type kvm with machine 'pc-q35-9.1' for virtualization type 'hvm' with architecture 'x86_64'

### ISSUE THREAD

**Issue by go9girl** [gamerhat18/Quick-VM#2]
When i try to start the VM out of the install script i always get the following error:
`Error launching details: Host does not support domain type kvm with machine 'pc-q35-9.1' for virtualization type 'hvm' with architecture 'x86_64'`
What am i doing wrong?

**Comment by thecmdrunner** [comment]
Hey @go9girl you sure you've enabled virtualization in your UEFI/BIOS?

**Comment by go9girl** [comment]
sorry for the extremly late response i had iommu set to auto not enabled changing that fixed that error.
